# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "version",
]

def version() -> builtins.str:
    r"""
    Returns the version of the native zero-server core.
    
    # Returns
    
    The version string of the `zero-ffi` crate the module was built against.
    
    # Errors
    
    Raises `RuntimeError` when the core reported no version, which only happens
    if the call panicked inside the core.
    """

