//! The static Huffman code of RFC 7541 Appendix B, which QPACK string literals
//! use "without modification" (RFC 9204 Section 4.1.2).
//!
//! The encoded data is "the bitwise concatenation of the codes corresponding to
//! each octet of the string literal", padded to an octet boundary with "the most
//! significant bits of the code corresponding to the EOS (end-of-string) symbol"
//! (RFC 7541 Section 5.2). The decoder enforces the three rules of that section:
//!
//! - "A padding strictly longer than 7 bits MUST be treated as a decoding error."
//! - "A padding not corresponding to the most significant bits of the code for
//!   the EOS symbol MUST be treated as a decoding error."
//! - "A Huffman-encoded string literal containing the EOS symbol MUST be treated
//!   as a decoding error."
//!
//! The code is canonical: the codes of each length form one contiguous range,
//! so the decoder reads one bit at a time and checks the code against the range
//! of its length. [`CODES`] is written into this file by a script from the
//! extracted Appendix B table; the four tables derived from it are generated by
//! the same script and rebuilt from [`CODES`] by a unit test.
//!
//! @see <https://www.rfc-editor.org/rfc/rfc7541.html#section-5.2>
//! @see <https://www.rfc-editor.org/rfc/rfc7541.html#appendix-B>

use alloc::vec::Vec;

/// The RFC 7541 Appendix B code: the code aligned to the least significant bit
/// and its length in bits, indexed by symbol, 256 being EOS.
///
/// @see <https://www.rfc-editor.org/rfc/rfc7541.html#appendix-B>
pub const CODES: [(u32, u8); 257] = [
    (0x1ff8, 13),
    (0x7fffd8, 23),
    (0xfffffe2, 28),
    (0xfffffe3, 28),
    (0xfffffe4, 28),
    (0xfffffe5, 28),
    (0xfffffe6, 28),
    (0xfffffe7, 28),
    (0xfffffe8, 28),
    (0xffffea, 24),
    (0x3ffffffc, 30),
    (0xfffffe9, 28),
    (0xfffffea, 28),
    (0x3ffffffd, 30),
    (0xfffffeb, 28),
    (0xfffffec, 28),
    (0xfffffed, 28),
    (0xfffffee, 28),
    (0xfffffef, 28),
    (0xffffff0, 28),
    (0xffffff1, 28),
    (0xffffff2, 28),
    (0x3ffffffe, 30),
    (0xffffff3, 28),
    (0xffffff4, 28),
    (0xffffff5, 28),
    (0xffffff6, 28),
    (0xffffff7, 28),
    (0xffffff8, 28),
    (0xffffff9, 28),
    (0xffffffa, 28),
    (0xffffffb, 28),
    (0x14, 6),
    (0x3f8, 10),
    (0x3f9, 10),
    (0xffa, 12),
    (0x1ff9, 13),
    (0x15, 6),
    (0xf8, 8),
    (0x7fa, 11),
    (0x3fa, 10),
    (0x3fb, 10),
    (0xf9, 8),
    (0x7fb, 11),
    (0xfa, 8),
    (0x16, 6),
    (0x17, 6),
    (0x18, 6),
    (0x0, 5),
    (0x1, 5),
    (0x2, 5),
    (0x19, 6),
    (0x1a, 6),
    (0x1b, 6),
    (0x1c, 6),
    (0x1d, 6),
    (0x1e, 6),
    (0x1f, 6),
    (0x5c, 7),
    (0xfb, 8),
    (0x7ffc, 15),
    (0x20, 6),
    (0xffb, 12),
    (0x3fc, 10),
    (0x1ffa, 13),
    (0x21, 6),
    (0x5d, 7),
    (0x5e, 7),
    (0x5f, 7),
    (0x60, 7),
    (0x61, 7),
    (0x62, 7),
    (0x63, 7),
    (0x64, 7),
    (0x65, 7),
    (0x66, 7),
    (0x67, 7),
    (0x68, 7),
    (0x69, 7),
    (0x6a, 7),
    (0x6b, 7),
    (0x6c, 7),
    (0x6d, 7),
    (0x6e, 7),
    (0x6f, 7),
    (0x70, 7),
    (0x71, 7),
    (0x72, 7),
    (0xfc, 8),
    (0x73, 7),
    (0xfd, 8),
    (0x1ffb, 13),
    (0x7fff0, 19),
    (0x1ffc, 13),
    (0x3ffc, 14),
    (0x22, 6),
    (0x7ffd, 15),
    (0x3, 5),
    (0x23, 6),
    (0x4, 5),
    (0x24, 6),
    (0x5, 5),
    (0x25, 6),
    (0x26, 6),
    (0x27, 6),
    (0x6, 5),
    (0x74, 7),
    (0x75, 7),
    (0x28, 6),
    (0x29, 6),
    (0x2a, 6),
    (0x7, 5),
    (0x2b, 6),
    (0x76, 7),
    (0x2c, 6),
    (0x8, 5),
    (0x9, 5),
    (0x2d, 6),
    (0x77, 7),
    (0x78, 7),
    (0x79, 7),
    (0x7a, 7),
    (0x7b, 7),
    (0x7ffe, 15),
    (0x7fc, 11),
    (0x3ffd, 14),
    (0x1ffd, 13),
    (0xffffffc, 28),
    (0xfffe6, 20),
    (0x3fffd2, 22),
    (0xfffe7, 20),
    (0xfffe8, 20),
    (0x3fffd3, 22),
    (0x3fffd4, 22),
    (0x3fffd5, 22),
    (0x7fffd9, 23),
    (0x3fffd6, 22),
    (0x7fffda, 23),
    (0x7fffdb, 23),
    (0x7fffdc, 23),
    (0x7fffdd, 23),
    (0x7fffde, 23),
    (0xffffeb, 24),
    (0x7fffdf, 23),
    (0xffffec, 24),
    (0xffffed, 24),
    (0x3fffd7, 22),
    (0x7fffe0, 23),
    (0xffffee, 24),
    (0x7fffe1, 23),
    (0x7fffe2, 23),
    (0x7fffe3, 23),
    (0x7fffe4, 23),
    (0x1fffdc, 21),
    (0x3fffd8, 22),
    (0x7fffe5, 23),
    (0x3fffd9, 22),
    (0x7fffe6, 23),
    (0x7fffe7, 23),
    (0xffffef, 24),
    (0x3fffda, 22),
    (0x1fffdd, 21),
    (0xfffe9, 20),
    (0x3fffdb, 22),
    (0x3fffdc, 22),
    (0x7fffe8, 23),
    (0x7fffe9, 23),
    (0x1fffde, 21),
    (0x7fffea, 23),
    (0x3fffdd, 22),
    (0x3fffde, 22),
    (0xfffff0, 24),
    (0x1fffdf, 21),
    (0x3fffdf, 22),
    (0x7fffeb, 23),
    (0x7fffec, 23),
    (0x1fffe0, 21),
    (0x1fffe1, 21),
    (0x3fffe0, 22),
    (0x1fffe2, 21),
    (0x7fffed, 23),
    (0x3fffe1, 22),
    (0x7fffee, 23),
    (0x7fffef, 23),
    (0xfffea, 20),
    (0x3fffe2, 22),
    (0x3fffe3, 22),
    (0x3fffe4, 22),
    (0x7ffff0, 23),
    (0x3fffe5, 22),
    (0x3fffe6, 22),
    (0x7ffff1, 23),
    (0x3ffffe0, 26),
    (0x3ffffe1, 26),
    (0xfffeb, 20),
    (0x7fff1, 19),
    (0x3fffe7, 22),
    (0x7ffff2, 23),
    (0x3fffe8, 22),
    (0x1ffffec, 25),
    (0x3ffffe2, 26),
    (0x3ffffe3, 26),
    (0x3ffffe4, 26),
    (0x7ffffde, 27),
    (0x7ffffdf, 27),
    (0x3ffffe5, 26),
    (0xfffff1, 24),
    (0x1ffffed, 25),
    (0x7fff2, 19),
    (0x1fffe3, 21),
    (0x3ffffe6, 26),
    (0x7ffffe0, 27),
    (0x7ffffe1, 27),
    (0x3ffffe7, 26),
    (0x7ffffe2, 27),
    (0xfffff2, 24),
    (0x1fffe4, 21),
    (0x1fffe5, 21),
    (0x3ffffe8, 26),
    (0x3ffffe9, 26),
    (0xffffffd, 28),
    (0x7ffffe3, 27),
    (0x7ffffe4, 27),
    (0x7ffffe5, 27),
    (0xfffec, 20),
    (0xfffff3, 24),
    (0xfffed, 20),
    (0x1fffe6, 21),
    (0x3fffe9, 22),
    (0x1fffe7, 21),
    (0x1fffe8, 21),
    (0x7ffff3, 23),
    (0x3fffea, 22),
    (0x3fffeb, 22),
    (0x1ffffee, 25),
    (0x1ffffef, 25),
    (0xfffff4, 24),
    (0xfffff5, 24),
    (0x3ffffea, 26),
    (0x7ffff4, 23),
    (0x3ffffeb, 26),
    (0x7ffffe6, 27),
    (0x3ffffec, 26),
    (0x3ffffed, 26),
    (0x7ffffe7, 27),
    (0x7ffffe8, 27),
    (0x7ffffe9, 27),
    (0x7ffffea, 27),
    (0x7ffffeb, 27),
    (0xffffffe, 28),
    (0x7ffffec, 27),
    (0x7ffffed, 27),
    (0x7ffffee, 27),
    (0x7ffffef, 27),
    (0x7fffff0, 27),
    (0x3ffffee, 26),
    (0x3fffffff, 30),
];

/// The EOS symbol.
pub const EOS: u16 = 256;

/// The longest code, in bits.
const MAX_CODE_LEN: u32 = 30;

/// The first code of each length from 0 to 30, zero for an unused length.
const FIRST: [u32; 31] = [
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14, 0x5c, 0xf8, 0x0, 0x3f8, 0x7fa, 0xffa, 0x1ff8, 0x3ffc,
    0x7ffc, 0x0, 0x0, 0x0, 0x7fff0, 0xfffe6, 0x1fffdc, 0x3fffd2, 0x7fffd8, 0xffffea, 0x1ffffec,
    0x3ffffe0, 0x7ffffde, 0xfffffe2, 0x0, 0x3ffffffc,
];

/// The number of codes of each length.
const COUNT: [u32; 31] = [
    0, 0, 0, 0, 0, 10, 26, 32, 6, 0, 5, 3, 2, 6, 2, 3, 0, 0, 0, 3, 8, 13, 26, 29, 12, 4, 15, 19,
    29, 0, 4,
];

/// The position in [`SYMBOLS`] of the first symbol of each length.
const INDEX: [u32; 31] = [
    0, 0, 0, 0, 0, 0, 10, 36, 68, 0, 74, 79, 82, 84, 90, 92, 0, 0, 0, 95, 98, 106, 119, 145, 174,
    186, 190, 205, 224, 0, 253,
];

/// The 257 symbols sorted by code length, then by symbol.
const SYMBOLS: [u16; 257] = [
    48, 49, 50, 97, 99, 101, 105, 111, 115, 116, 32, 37, 45, 46, 47, 51, 52, 53, 54, 55, 56, 57,
    61, 65, 95, 98, 100, 102, 103, 104, 108, 109, 110, 112, 114, 117, 58, 66, 67, 68, 69, 70, 71,
    72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 89, 106, 107, 113, 118, 119,
    120, 121, 122, 38, 42, 44, 59, 88, 90, 33, 34, 40, 41, 63, 39, 43, 124, 35, 62, 0, 36, 64, 91,
    93, 126, 94, 125, 60, 96, 123, 92, 195, 208, 128, 130, 131, 162, 184, 194, 224, 226, 153, 161,
    167, 172, 176, 177, 179, 209, 216, 217, 227, 229, 230, 129, 132, 133, 134, 136, 146, 154, 156,
    160, 163, 164, 169, 170, 173, 178, 181, 185, 186, 187, 189, 190, 196, 198, 228, 232, 233, 1,
    135, 137, 138, 139, 140, 141, 143, 147, 149, 150, 151, 152, 155, 157, 158, 165, 166, 168, 174,
    175, 180, 182, 183, 188, 191, 197, 231, 239, 9, 142, 144, 145, 148, 159, 171, 206, 215, 225,
    236, 237, 199, 207, 234, 235, 192, 193, 200, 201, 202, 205, 210, 213, 218, 219, 238, 240, 242,
    243, 255, 203, 204, 211, 212, 214, 221, 222, 223, 241, 244, 245, 246, 247, 248, 250, 251, 252,
    253, 254, 2, 3, 4, 5, 6, 7, 8, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28,
    29, 30, 31, 127, 220, 249, 10, 13, 22, 256,
];

/// Why a Huffman string was refused (RFC 7541 Section 5.2).
///
/// @see <https://www.rfc-editor.org/rfc/rfc7541.html#section-5.2>
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HuffmanError {
    /// More than 7 bits of padding.
    Padding,
    /// Padding that is not the most significant bits of EOS.
    PaddingNotEos,
    /// The EOS symbol inside the data.
    Eos,
    /// The output slice is too short (slice API only).
    OutputFull,
}

impl HuffmanError {
    /// The name used in conformance vectors.
    ///
    /// # Returns
    ///
    /// `"padding"`, `"paddingNotEos"`, `"eos"` or `"outputFull"`.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Padding => "padding",
            Self::PaddingNotEos => "paddingNotEos",
            Self::Eos => "eos",
            Self::OutputFull => "outputFull",
        }
    }
}

/// The entry of `table` at `index`, read without indexing.
fn at<T: Copy>(table: &[T], index: u32) -> Option<T> {
    table.get(usize::try_from(index).ok()?).copied()
}

/// The most octets `encoded_len` Huffman octets can decode to.
///
/// That is floor(8n / 5), since the shortest code is 5 bits, computed as
/// 8 * (n / 5) + floor(8 * (n % 5) / 5) with saturating operations: exact for
/// every slice length, and `usize::MAX` for a larger argument, which no slice
/// has.
///
/// # Arguments
///
/// * `encoded_len` - the length of the Huffman-encoded data.
///
/// # Returns
///
/// The bound in octets.
#[must_use]
pub const fn decoded_len_bound(encoded_len: usize) -> usize {
    let whole = match encoded_len.checked_div(5) {
        Some(whole) => whole,
        None => 0,
    };
    let part = match encoded_len.checked_rem(5) {
        Some(part) => part,
        None => 0,
    };
    let tail = match part.saturating_mul(8).checked_div(5) {
        Some(tail) => tail,
        None => 0,
    };
    whole.saturating_mul(8).saturating_add(tail)
}

/// The octets [`encode`] writes for `input`.
///
/// The bit count is summed in `u64`, so a 32-bit target never overflows.
///
/// # Arguments
///
/// * `input` - the octets to encode.
///
/// # Returns
///
/// ceil(sum of the code lengths / 8).
#[must_use]
pub fn encoded_len(input: &[u8]) -> u64 {
    let bits = input.iter().fold(0u64, |bits, &octet| {
        let (_, len) = CODES.get(usize::from(octet)).copied().unwrap_or((0, 0));
        bits.saturating_add(u64::from(len))
    });
    bits.saturating_add(7).checked_shr(3).unwrap_or(0)
}

/// Appends the Huffman encoding of `input` to `out`, padded to an octet
/// boundary with the most significant bits of EOS (all ones).
///
/// @see <https://www.rfc-editor.org/rfc/rfc7541.html#section-5.2>
///
/// # Arguments
///
/// * `input` - the octets to encode.
/// * `out` - the buffer the encoding is appended to.
pub fn encode(input: &[u8], out: &mut Vec<u8>) {
    out.reserve(usize::try_from(encoded_len(input)).unwrap_or(0));
    let mut pending = 0u64;
    let mut bits = 0u32;
    for &octet in input {
        let (code, len) = CODES.get(usize::from(octet)).copied().unwrap_or((0, 0));
        let len = u32::from(len);
        pending = pending.checked_shl(len).unwrap_or(0) | u64::from(code);
        bits = bits.saturating_add(len);
        while bits >= 8 {
            bits = bits.saturating_sub(8);
            let [low, ..] = pending.checked_shr(bits).unwrap_or(0).to_le_bytes();
            out.push(low);
        }
        pending &= 1u64.checked_shl(bits).unwrap_or(0).wrapping_sub(1);
    }
    if bits > 0 {
        let pad = 8u32.saturating_sub(bits);
        let ones = 1u64.checked_shl(pad).unwrap_or(0).wrapping_sub(1);
        let [low, ..] = (pending.checked_shl(pad).unwrap_or(0) | ones).to_le_bytes();
        out.push(low);
    }
}

/// Decodes `input` and hands each decoded octet to `emit`.
fn decode_with(
    input: &[u8],
    mut emit: impl FnMut(u8) -> Result<(), HuffmanError>,
) -> Result<(), HuffmanError> {
    let mut code = 0u32;
    let mut len = 0u32;
    for &octet in input {
        for shift in (0..8u32).rev() {
            let bit = u32::from(octet.checked_shr(shift).unwrap_or(0) & 1);
            code = code.checked_shl(1).unwrap_or(0) | bit;
            len = len.saturating_add(1);
            let first = at(&FIRST, len).unwrap_or(0);
            let count = at(&COUNT, len).unwrap_or(0);
            match code.checked_sub(first) {
                Some(offset) if offset < count => {
                    let position = at(&INDEX, len).unwrap_or(0).saturating_add(offset);
                    let symbol = at(&SYMBOLS, position).unwrap_or(EOS);
                    let octet = u8::try_from(symbol).map_err(|_| HuffmanError::Eos)?;
                    emit(octet)?;
                    code = 0;
                    len = 0;
                }
                _ if len >= MAX_CODE_LEN => return Err(HuffmanError::Padding),
                _ => {}
            }
        }
    }
    if len > 7 {
        return Err(HuffmanError::Padding);
    }
    if code.count_ones() != len {
        return Err(HuffmanError::PaddingNotEos);
    }
    Ok(())
}

/// Decodes `input` into `out`.
///
/// @see <https://www.rfc-editor.org/rfc/rfc7541.html#section-5.2>
///
/// # Arguments
///
/// * `input` - the Huffman-encoded data.
/// * `out` - receives the decoded octets from its start.
///
/// # Returns
///
/// The octets written.
///
/// # Errors
///
/// [`HuffmanError::Padding`], [`HuffmanError::PaddingNotEos`] and
/// [`HuffmanError::Eos`] for the RFC 7541 Section 5.2 rules, and
/// [`HuffmanError::OutputFull`] when `out` is too short.
pub fn decode(input: &[u8], out: &mut [u8]) -> Result<usize, HuffmanError> {
    let mut slots = out.iter_mut();
    let mut written = 0usize;
    decode_with(input, |octet| {
        let slot = slots.next().ok_or(HuffmanError::OutputFull)?;
        *slot = octet;
        written = written.saturating_add(1);
        Ok(())
    })?;
    Ok(written)
}

/// Decodes `input`, appending to `out` after reserving
/// [`decoded_len_bound`]`(input.len())` octets.
///
/// @see <https://www.rfc-editor.org/rfc/rfc7541.html#section-5.2>
///
/// # Arguments
///
/// * `input` - the Huffman-encoded data.
/// * `out` - the buffer the decoded octets are appended to; on an error it holds
///   the octets decoded before the fault.
///
/// # Errors
///
/// [`HuffmanError::Padding`], [`HuffmanError::PaddingNotEos`] and
/// [`HuffmanError::Eos`]; never [`HuffmanError::OutputFull`].
pub fn decode_to_vec(input: &[u8], out: &mut Vec<u8>) -> Result<(), HuffmanError> {
    out.reserve(decoded_len_bound(input.len()));
    decode_with(input, |octet| {
        out.push(octet);
        Ok(())
    })
}

#[cfg(test)]
mod tests {
    use alloc::vec::Vec;

    use super::{
        decode, decode_to_vec, decoded_len_bound, encode, encoded_len, HuffmanError, CODES, COUNT,
        EOS, FIRST, INDEX, SYMBOLS,
    };
    use crate::unhex;
    use crate::xorshift::XorShift;

    /// Decodes `input` into a fresh vector.
    fn decoded(input: &[u8]) -> Result<Vec<u8>, HuffmanError> {
        let mut out = Vec::new();
        decode_to_vec(input, &mut out).map(|()| out)
    }

    /// Encodes `input` into a fresh vector.
    fn encoded(input: &[u8]) -> Vec<u8> {
        let mut out = Vec::new();
        encode(input, &mut out);
        out
    }

    /// The bits of `codes` concatenated, most significant first, and padded with
    /// one bits to an octet boundary.
    fn pack(codes: &[(u32, u32)]) -> Vec<u8> {
        let mut bits: Vec<bool> = Vec::new();
        for &(code, len) in codes {
            for shift in (0..len).rev() {
                bits.push(code.checked_shr(shift).unwrap_or(0) & 1 == 1);
            }
        }
        bits.chunks(8)
            .map(|chunk| {
                (0..8usize).fold(0u8, |octet, position| {
                    let bit = chunk.get(position).copied().unwrap_or(true);
                    octet.wrapping_shl(1) | u8::from(bit)
                })
            })
            .collect()
    }

    /// RFC 7541 Section 5.2: "String literals that use Huffman encoding are
    /// encoded with the Huffman code defined in Appendix B (see examples for
    /// requests in Appendix C.4 and for responses in Appendix C.6)."
    #[test]
    fn huffman_literals_of_appendix_c_4_and_c_6_decode_and_encode_to_the_published_octets() {
        let cases: [(&str, &[u8], &str); 12] = [
            ("C.4.1", b"www.example.com", "f1e3c2e5f23a6ba0ab90f4ff"),
            ("C.4.2", b"no-cache", "a8eb10649cbf"),
            ("C.4.3", b"custom-key", "25a849e95ba97d7f"),
            ("C.4.3", b"custom-value", "25a849e95bb8e8b4bf"),
            ("C.6.1", b"302", "6402"),
            ("C.6.1", b"private", "aec3771a4b"),
            (
                "C.6.1",
                b"Mon, 21 Oct 2013 20:13:21 GMT",
                "d07abe941054d444a8200595040b8166e082a62d1bff",
            ),
            (
                "C.6.1",
                b"https://www.example.com",
                "9d29ad171863c78f0b97c8e9ae82ae43d3",
            ),
            ("C.6.2", b"307", "640eff"),
            (
                "C.6.3",
                b"Mon, 21 Oct 2013 20:13:22 GMT",
                "d07abe941054d444a8200595040b8166e084a62d1bff",
            ),
            ("C.6.3", b"gzip", "9bd9ab"),
            (
                "C.6.3",
                b"foo=ASDJKHQKBZXOQWEOPIUAXQWEOIU; max-age=3600; version=1",
                "94e7821dd7f2e6c7b335dfdfcd5b3960d5af27087f3672c1ab270fb5291f9587316065c003ed4ee5b1063d5007",
            ),
        ];
        for (section, text, hex) in cases {
            let published = unhex(hex);
            assert_eq!(decoded(&published), Ok(text.to_vec()), "{section}");
            assert_eq!(encoded(text), published, "{section}");
            assert_eq!(
                Some(encoded_len(text)),
                u64::try_from(published.len()).ok(),
                "{section}"
            );
            let mut slice = [0u8; 64];
            assert_eq!(decode(&published, &mut slice), Ok(text.len()), "{section}");
            assert_eq!(slice.get(..text.len()), Some(text), "{section}");
        }
    }

    /// RFC 7541 Section 5.2: "A padding strictly longer than 7 bits MUST be
    /// treated as a decoding error."
    #[test]
    fn huffman_padding_strictly_longer_than_7_bits_is_a_decoding_error() {
        assert_eq!(encoded(b"&"), unhex("f8"));
        assert_eq!(decoded(&unhex("f8ff")), Err(HuffmanError::Padding));
        assert_eq!(decoded(&unhex("ff")), Err(HuffmanError::Padding));
        let mut long = encoded(b"a");
        long.push(0xff);
        assert_eq!(decoded(&long), Err(HuffmanError::Padding));
        assert_eq!(decoded(&unhex("f8")), Ok(b"&".to_vec()));
    }

    /// RFC 7541 Section 5.2: "A padding not corresponding to the most
    /// significant bits of the code for the EOS symbol MUST be treated as a
    /// decoding error."
    #[test]
    fn huffman_padding_not_corresponding_to_the_eos_prefix_is_a_decoding_error() {
        assert_eq!(encoded(b"a"), unhex("1f"));
        assert_eq!(decoded(&unhex("1e")), Err(HuffmanError::PaddingNotEos));
        assert_eq!(decoded(&unhex("18")), Err(HuffmanError::PaddingNotEos));
        assert_eq!(decoded(&unhex("00")), Err(HuffmanError::PaddingNotEos));
        assert_eq!(decoded(&unhex("1f")), Ok(b"a".to_vec()));
        assert_eq!(decoded(&unhex("6402")), Ok(b"302".to_vec()));
    }

    /// RFC 7541 Section 5.2: "A Huffman-encoded string literal containing the
    /// EOS symbol MUST be treated as a decoding error."
    #[test]
    fn a_huffman_encoded_string_containing_the_eos_symbol_is_a_decoding_error() {
        assert_eq!(decoded(&unhex("ffffffff")), Err(HuffmanError::Eos));
        let (a, a_len) = CODES.get(usize::from(b'a')).copied().unwrap_or_default();
        let (eos, eos_len) = CODES.get(usize::from(EOS)).copied().unwrap_or_default();
        let inner = pack(&[
            (a, u32::from(a_len)),
            (eos, u32::from(eos_len)),
            (a, u32::from(a_len)),
        ]);
        assert_eq!(decoded(&inner), Err(HuffmanError::Eos));
        let trailing = pack(&[(a, u32::from(a_len)), (eos, u32::from(eos_len))]);
        assert_eq!(decoded(&trailing), Err(HuffmanError::Eos));
    }

    #[test]
    fn the_code_table_is_complete_and_matches_the_appendix_b_examples() {
        let kraft = CODES.iter().fold(0u64, |sum, &(_, len)| {
            sum.saturating_add(1u64.wrapping_shl(30u32.saturating_sub(u32::from(len))))
        });
        assert_eq!(kraft, 1u64.wrapping_shl(30));
        assert_eq!(CODES.get(47).copied(), Some((0x18, 6)));
        assert_eq!(
            CODES.get(usize::from(EOS)).copied(),
            Some((0x3fff_ffff, 30))
        );
        assert!(CODES.iter().all(|&(code, len)| {
            (5..=30).contains(&len) && code < 1u32.wrapping_shl(u32::from(len))
        }));
    }

    /// RFC 7541 Appendix B: "It is a canonical Huffman code", so the
    /// first-code, count and index tables of the decoder rebuild from the code
    /// table: the codes of each length are contiguous.
    #[test]
    fn the_canonical_decoding_tables_rebuild_from_the_codes() {
        let mut order: Vec<u16> = (0..=EOS).collect();
        order.sort_by_key(|&symbol| {
            let (_, len) = CODES.get(usize::from(symbol)).copied().unwrap_or_default();
            (len, symbol)
        });
        assert_eq!(order.as_slice(), SYMBOLS.as_slice());
        let mut first = [0u32; 31];
        let mut count = [0u32; 31];
        let mut index = [0u32; 31];
        let mut position = 0u32;
        for (len, ((first, count), index)) in
            (0u8..).zip(first.iter_mut().zip(count.iter_mut()).zip(index.iter_mut()))
        {
            let mut codes: Vec<u32> = CODES
                .iter()
                .filter(|&&(_, length)| length == len)
                .map(|&(code, _)| code)
                .collect();
            codes.sort_unstable();
            let Some(&lowest) = codes.first() else {
                continue;
            };
            let expected: Vec<u32> = (0u32..)
                .map(|offset| lowest.saturating_add(offset))
                .take(codes.len())
                .collect();
            assert_eq!(codes, expected, "codes of length {len} are contiguous");
            *first = lowest;
            *count = u32::try_from(codes.len()).unwrap_or_default();
            *index = position;
            position = position.saturating_add(*count);
        }
        assert_eq!(first, FIRST);
        assert_eq!(count, COUNT);
        assert_eq!(index, INDEX);
    }

    /// RFC 7541 Section 5.2: "The encoded data is the bitwise concatenation of
    /// the codes corresponding to each octet of the string literal.", padded
    /// with the most significant bits of EOS, so each of the 256 octets
    /// decodes back alone.
    #[test]
    fn every_symbol_round_trips_alone() {
        for symbol in 0..=255u8 {
            let alone = [symbol];
            let out = encoded(&alone);
            assert_eq!(decoded(&out), Ok(alone.to_vec()), "{symbol}");
        }
        assert_eq!(encoded(b""), Vec::<u8>::new());
        assert_eq!(decoded(b""), Ok(Vec::new()));
    }

    /// RFC 7541 Appendix C.4.1: the Huffman-encoded `www.example.com`
    /// decodes into a 15-octet slice and reports a 14-octet one as too short,
    /// a local condition RFC 7541 Section 5.2 does not name.
    #[test]
    fn the_slice_decoder_reports_a_short_output() {
        let published = unhex("f1e3c2e5f23a6ba0ab90f4ff");
        let mut short = [0u8; 14];
        assert_eq!(
            decode(&published, &mut short),
            Err(HuffmanError::OutputFull)
        );
        let mut exact = [0u8; 15];
        assert_eq!(decode(&published, &mut exact), Ok(15));
    }

    /// RFC 7541 Appendix B: the shortest code is 5 bits long (the `len`
    /// column), so n encoded octets decode to at most floor(8n / 5) octets.
    #[test]
    fn the_decoded_length_bound_is_floor_of_8n_over_5() {
        for n in 0..1_000usize {
            assert_eq!(
                decoded_len_bound(n),
                n.saturating_mul(8).div_euclid(5),
                "{n}"
            );
        }
        let largest = isize::MAX.unsigned_abs();
        let exact = u128::try_from(largest)
            .unwrap_or_default()
            .saturating_mul(8)
            .div_euclid(5);
        assert_eq!(u128::try_from(decoded_len_bound(largest)).ok(), Some(exact));
        assert_eq!(decoded_len_bound(usize::MAX), usize::MAX);
        let shortest = encoded(&[b'0'; 8]);
        assert_eq!(shortest.len(), 5);
        assert_eq!(decoded_len_bound(shortest.len()), 8);
    }

    /// RFC 7541 Section 5.2: the String Length of a Huffman literal is "The
    /// number of octets used to encode the string literal", so the encoded
    /// length computed ahead of encoding is exact and the octets decode back.
    #[test]
    fn random_strings_round_trip_and_their_encoded_length_is_exact() {
        let mut rng = XorShift::new(0x4855_0001);
        for _ in 0..crate::xorshift::iterations(3_000) {
            let text = rng.bytes(0, 64);
            let out = encoded(&text);
            assert_eq!(u64::try_from(out.len()).ok(), Some(encoded_len(&text)));
            assert_eq!(decoded(&out), Ok(text.clone()));
            assert!(text.len() <= decoded_len_bound(out.len()));
        }
    }

    /// RFC 7541 Section 5.2: arbitrary octets read as Huffman data never panic
    /// the decoder, which either reports one of the decoding errors that
    /// section names or yields octets that encode back to the same text.
    #[test]
    fn arbitrary_octets_never_panic_the_huffman_decoder() {
        let mut rng = XorShift::new(0x4855_0002);
        for _ in 0..crate::xorshift::iterations(20_000) {
            let input = rng.bytes(0, 40);
            let mut out = alloc::vec![0u8; decoded_len_bound(input.len())];
            let slice = decode(&input, &mut out);
            assert_ne!(slice, Err(HuffmanError::OutputFull));
            if let Ok(text) = decoded(&input) {
                assert_eq!(slice, Ok(text.len()));
                assert_eq!(decoded(&encoded(&text)), Ok(text));
            }
        }
    }
}
