/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Returns the version of the native zero-server core.
 *
 * # Returns
 *
 * The version string of the `zero-ffi` crate the addon was built against.
 *
 * # Errors
 *
 * Rejects when the core reported no version, which only happens if the call
 * panicked inside the core.
 */
export declare function version(): string
