/* zero-server C ABI.
 *
 * An enum the caller passes in, as an argument or as a field of a struct, must hold one of
 * the values the enum declares. The library reads it as one of those values, and any other
 * value is undefined behavior. */

#pragma once

/* Generated by cbindgen from crates/zero-ffi. Do not edit by hand; run `cargo build -p zero-ffi` to regenerate. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the version of the zero-server core.
//
// # Returns
//
// A pointer to a null-terminated UTF-8 string owned by the library and valid for
// the lifetime of the process, or null if the call panicked. The caller must not
// free it.
const char *zero_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
